name: Claude Code Review

on:
  pull_request_target:
    types: [opened, ready_for_review]
    # Optional: Only run on specific file changes
    # paths:
    #   - "src/**/*.cpp"
    #   - "src/**/*.h"
    #   - "src/**/*.py"

jobs:
  claude-review:
    # Optional: Filter by PR author
    # if: |
    #   github.event.pull_request.user.login == 'external-contributor' ||
    #   github.event.pull_request.user.login == 'new-developer' ||
    #   github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          allowed_non_write_users: '*'
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            Review this pull request for any issues. Be concise and to the point.

            Check for:
            - Bugs, crashes, undefined behavior
            - Memory leaks, resource management issues
            - Thread safety problems
            - Security vulnerabilities
            - Performance issues
            - Logic errors
            - Code style/guidelines violations (see docs/CONTRIBUTING.md)

            IMPORTANT - Format your review concisely:
            - Group issues by severity: **Critical**, **Must Fix**, **Medium**, **Low**, **Minor**
            - For each issue: state the problem and solution only, nothing more
            - Skip positive feedback and explanations of what's working well
            - Report all issues you find (critical to minor), but keep each concise

            After your review:
            1. If you found issues: Use `gh pr comment` to post them as a comment
            2. If everything looks good: Use `gh pr review --approve` to explicitly approve the PR with message "Code review passed - no issues found."

          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.claude.com/en/docs/claude-code/cli-reference for available options
          claude_args: '--allowed-tools "Bash(gh issue view:*),Bash(gh search:*),Bash(gh issue list:*),Bash(gh pr comment:*),Bash(gh pr review:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr list:*)"'
